name: konselingku
version: 1.0.0+7
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.3.0
  flutter_svg: ^1.0.3
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.9
  url_launcher: ^6.0.20
  firebase_messaging: ^11.2.8
  http: ^0.13.4
  flutter: 
    sdk: flutter
  background_locator: 
    git: https://github.com/caiobraga/background_locator
  flutter_map: ^0.14.0
  geolocator: ^8.2.1
  tuple: ^2.0.0
  latlong2: ^0.8.1
  permission_handler: ^9.2.0
  get_cli: ^1.8.0
  flutter_local_notifications: ^9.7.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

